config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#index'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :events
  get    '/events/:id/invitation', to: 'event_invitations#new', as: 'new_invitation'
  post   'event_invitations' => 'event_invitations#create'
  
  get    '/events/:id/add_admin', to: 'event_managements#new', as: 'new_admin'
  post   'event_managements' => 'event_managements#create'

  get    '/invites', to: 'event_invitations#index', as: 'invites'

  put    '/invites/:id/accept', to: 'event_invitations#accept', as: 'accept_invite'
  put    '/invites/:id/decline', to: 'event_invitations#decline', as: 'decline_invite'
  get    '/invites/:id',         to: 'event_invitations#show', as: 'event_invitation'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def index
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_dashboard.html.erb
<div class="center jumbotron">
  <h1>Event Dashboard</h1>
  <h2>
  	Total Events: <%= current_user.attended_events.count  %><br>
    Upcoming Events: <%= current_user.upcoming_events.count %>
    										<br>
    Pending Events: <%= current_user.pending_events.count %><br>
  </h2>
	<%= link_to "Create an event!", new_event_path, class: "btn btn-lg btn-primary" %>
</div>
<div class="row">
	<div class="col-xs-6">
		<div class="panel panel-info">
			<div class="panel panel-heading">Upcoming Events</div>
			<div class="panel panel-body" style="margin-bottom: 0px">
				<% if current_user.upcoming_events.any? %>
					<ul>
						<% current_user.upcoming_events.each do |event| %>
							<li><%= link_to "#{event.title} - #{event.datetime.strftime('%m/%d/%Y')}", event %></li>
						<% end %>
					</ul>
				<% else %>
					<p>No upcoming events!</p>
				<% end %>
			</div>
		</div>
	</div>
	<div class="col-xs-6">
		<div class="panel panel-info">
			<div class="panel panel-heading">Past Events</div>
			<div class="panel panel-body" style="margin-bottom: 0px">
				<% if current_user.previous_events.any? %>
					<ul>
						<% current_user.previous_events.each do |event| %>
							<li><%= link_to "#{event.title} - #{event.datetime.strftime('%m/%d/%Y')}", event %></li>
						<% end %>
					</ul>
				<% else %>
					<p>You have no past events.</p>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/static_pages/_welcome.html.erb
<div class="center jumbotron">
  <h1>Welcome to Evently</h1>

  <h2>
    This is the home page for the evently app. You can create an account, create events, and invite people to events.
  </h2>
	<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/static_pages/index.html.erb
<% if signed_in? %>
	<%= render 'dashboard' %>
<% else %>
	<%= render 'welcome' %>
<% end %>