config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#index'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :events
  get    '/events/:id/invitation', to: 'event_invitations#new', as: 'new_invitation'
  post   'event_invitations' => 'event_invitations#create'
  
  get    '/events/:id/add_admin', to: 'event_managements#new', as: 'new_admin'
  post   'event_managements' => 'event_managements#create'

  get    '/invites', to: 'event_invitations#index', as: 'invites'

  put    '/invites/:id/accept', to: 'event_invitations#accept', as: 'accept_invite'
  put    '/invites/:id/decline', to: 'event_invitations#decline', as: 'decline_invite'
  get    '/invites/:id',         to: 'event_invitations#show', as: 'event_invitation'
end

app/models/event.rb
class Event < ActiveRecord::Base
  after_create :assign_creator_to_attendees
  belongs_to :creator, :class_name => "User"
  has_many :invitations, :class_name => "EventInvitation"
  has_many :invitees, :through => :invitations
  has_many :pending_invitees, -> { where event_invitations: {attending: nil }},
                                  :through => :invitations,
                                  source: :invitee
  has_many :attendees, -> { where event_invitations: {attending: true} },
                          :through => :invitations,
                          source: :invitee
  has_many :absentees, -> { where event_invitations: {attending: false} },
                          :through => :invitations,
                          source: :invitee
  has_many :managements, :class_name => "EventManagement"
  has_many :admins, :through => :managements

  def Event.past
    Event.where('datetime < ?', Time.now)
  end

  def Event.upcoming
    Event.where('datetime > ?', Time.now)
  end

  def admin_or_creator?(user)
    self.admins.include?(user) || self.creator == user ? true : false
  end

  private

    def assign_creator_to_attendees
      self.invitations.build(inviter_id: self.creator.id, invitee_id: self.creator.id, attending: true).save
    end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.hosted_events.build(event_params)
    if @event.save
      flash[:success] = "Event created!"
      redirect_to events_path
    else
      flash.now[:danger] = "Error creating event."
      render 'new'
    end
  end

  private

    def event_params
      params.require(:event).permit(:title, :location, :description, :datetime, :creator_id)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
<h2>Events</h2>
<ul class="nav nav-tabs">
  <li class="active">
  	<a data-toggle="tab" href="#upcoming">
  		<h4>
  			<%= @events.upcoming.any? ? "Upcoming(#{@events.upcoming.count})" : "Upcoming" %>
			</h4>
		</a>
	</li>
  <li>
  	<a data-toggle="tab" href="#past">
  		<h4>
  			Past
			</h4>
		</a>
	</li>
</ul>

<div class="tab-content">
  <div id="upcoming" class="tab-pane fade in active">
    <table class="table table-striped">
    	<thead>
    		<tr>
    			<th>Title</th>
    			<th>Location</th>
    			<th>Host</th>
    			<th>Date & Time</th>
    		</tr>
    	</thead>
    	<tbody>
    		<% @events.upcoming.each do |event| %>
	    		<tr>
	    			<td><%= link_to event.title %></td>
	    			<td><%= event.location %></td>
	    			<td><%= link_to event.creator.full_name, event.creator %></td>
	    			<td><%= event.datetime.localtime.strftime('%m/%d/%Y, %l:%M %p') %></td>
	    		</tr>
    		<% end %>
    	</tbody>
    </table>
    
  </div>
  <div id="past" class="tab-pane fade">
    <table class="table table-striped">
    	<thead>
    		<tr>
    			<th>Title</th>
    			<th>Location</th>
    			<th>Host</th>
    			<th>Date & Time</th>
    		</tr>
    	</thead>
    	<tbody>
    		<% @events.past.each do |event| %>
	    		<tr>
	    			<td><%= link_to event.title %></td>
	    			<td><%= event.location %></td>
	    			<td><%= link_to event.creator.full_name, event.creator %></td>
	    			<td><%= event.datetime.localtime.strftime('%m/%d/%Y, %l:%M %p') %></td>
	    		</tr>
    		<% end %>
    	</tbody>
    </table>
  </div>

</div>

app/views/events/new.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<div class="panel panel-success">
			<div class="panel-heading"><h4>Create event</h4></div>
			<div class="panel-body">
				<%= form_for @event do |f| %>
					<div class="form-group">
						<%= f.label :title %>
						<%= f.text_field :title, class: 'form-control', placeholder: "My Birthday Party" %>
					</div>

					<div class="form-group">
						<%= f.label :description %>
						<%= f.text_area :description, class: 'form-control', rows: '7', 
														placeholder: "Let's meetup and have a great time!" %>
					</div>

					<div class="form-group">
						<%= f.label :location %>
						<%= f.text_field :location, class: 'form-control', 
														 placeholder: "30 Rockefeller Plaza, NYC" %>
					</div>

					<div class="form-group">
						<%= f.label :datetime, "Date and Time" %>
						<%= f.datetime_select :datetime, class: 'datepicker' %>
					</div>
					
					<div class="form-group">
						<%= f.submit "Create", class: 'btn btn-success' %>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/events/show.html.erb
<h1>Event Page</h1>
<strong>Title:</strong> <%= @event.title %> <br/>
<strong>Created By:</strong> <%= link_to @event.creator.full_name, @event.creator if @event.creator %><br />
<strong>Time and Date:</strong> <%= @event.datetime %><br/><br/>
<strong>Admins:</strong>
<ul>
	<% @event.admins.each do |admin| %>
		<li><%= link_to admin.full_name, admin %></li>
	<% end %>
</ul>


<strong>Pending:</strong> 
<ul>
	<% @event.pending_invitees.each do |pending_invitee| %>
		<li><%= link_to pending_invitee.full_name, pending_invitee %></li>
	<% end %>
</ul><br/>

<strong>Attending:</strong> 
<ul>
	<% @event.attendees.each do |attendee| %>
		<li><%= link_to attendee.full_name, attendee %></li>
	<% end %>
</ul><br/>

<strong>Declined:</strong> 
<ul>
	<% @event.absentees.each do |absentee| %>
		<li><%= link_to absentee.full_name, absentee %></li>
	<% end %>
</ul><br/>

<%= link_to "Send Invite", new_invitation_path if @event.admin_or_creator?(current_user) %><br>

<%= link_to "Add admins", new_admin_path if @event.admin_or_creator?(current_user) %>