config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#index'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :events
  get    '/events/:id/invitation', to: 'event_invitations#new', as: 'new_invitation'
  post   'event_invitations' => 'event_invitations#create'
  
  get    '/events/:id/add_admin', to: 'event_managements#new', as: 'new_admin'
  post   'event_managements' => 'event_managements#create'

  get    '/invites', to: 'event_invitations#index', as: 'invites'

  put    '/invites/:id/accept', to: 'event_invitations#accept', as: 'accept_invite'
  put    '/invites/:id/decline', to: 'event_invitations#decline', as: 'decline_invite'
  get    '/invites/:id',         to: 'event_invitations#show', as: 'event_invitation'
end

app/models/event_invitation.rb
class EventInvitation < ActiveRecord::Base
  validate :inviter_is_event_creator_or_admin
  validates_uniqueness_of :event_id, scope: [:invitee_id]
  #validates_presence_of :inviter_id, :if => :event_creator?
  belongs_to :event
  belongs_to :inviter, :class_name => "User"
  belongs_to :invitee, :class_name => "User"

  def inviter_is_event_creator_or_admin
    if self.event.creator == self.inviter
      true
    elsif self.event.admins.include?(self.inviter)
      true
    else
      errors.add(:base, "Only admins or host can invite guests")
    end
  end

  def status
    case self.attending
    when true
      'Accepted'
    when false
      'Declined'
    when nil
      'Pending'
    end
  end
end

app/controllers/event_invitations_controller.rb
class EventInvitationsController < ApplicationController
  def index
    if current_user.nil?
      @sent_invitations = []
      @received_invitations = []
    else
      @sent_invitations = current_user.sent_invitations
      @received_invitations = current_user.received_invitations
    end
  end

  def show
    @action = params[:action]
    @invitation = EventInvitation.find(params[:id])
  end

  def new
    @event = Event.find(params[:id])
    @invitation = EventInvitation.new(:event_id => params[:id])
  end

  def create
    # set the invitee by email. if invitee is not in database, render error
    if @invitee = User.where(email: params[:event_invitation][:invitee].downcase).first
      @invitation = EventInvitation.new(invitation_params)
      if @invitation.save
        flash[:success] = "Invitation sent to #{@invitee.email}!"
        redirect_to events_path
      else
        flash[:danger] = "Error sending invitation. The user may have already been invited or you are not the host."
        event_id = params[:event_invitation][:event_id]
        redirect_to new_invitation_path(event_id)
      end
    else
      flash[:danger] = "Invitee email not found."
      event_id = params[:event_invitation][:event_id]
      redirect_to new_invitation_path(event_id)
    end
  end

  def accept
    @invite = EventInvitation.find(params[:id])
    @invite.update_attributes(attending: true)
    if @action == 'show' 
      redirect_to @invite 
    else
      redirect_to invites_path
    end
  end

  def decline
    @invite = EventInvitation.find(params[:id])
    @invite.update_attributes(attending: false)
    redirect_to invites_path
  end

  private

    def invitation_params
      params[:event_invitation][:invitee_id] = @invitee.id
      params[:event_invitation][:inviter_id] = current_user.id
      params.require(:event_invitation).permit(:message, :event_id, :invitee_id, :inviter_id)
    end
end

app/helpers/event_invitations_helper.rb
module EventInvitationsHelper
end

app/views/event_invitations/index.html.erb
<h2>Invites</h2>
<ul class="nav nav-tabs">
  <li class="active"><a data-toggle="tab" href="#inbox">Inbox</a></li>
  <li><a data-toggle="tab" href="#sent">Sent</a></li>
</ul>

<div class="tab-content">
  <div id="inbox" class="tab-pane fade in active">
    <h3>Inbox</h3>
    <table class="table table-striped">
    	<thead>
    		<tr>
    			<th>From</th>
    			<th>Event</th>
    			<th>Date & Time</th>
    			<th>Status</th>
    			<th>Actions</th>
    			<th>View</th>
    		</tr>
    	</thead>
    	<tbody>
    		<% @received_invitations.each do |rec_invite| %>
    		<tr>
    			<td><%= link_to rec_invite.inviter.full_name, rec_invite.inviter %></td>
    			<td><%= link_to rec_invite.event.title, rec_invite.event %></td>
    			<td><%= rec_invite.event.datetime.localtime.strftime('%m/%d/%Y, %l:%M %p') %></td>
    			<td><%= rec_invite.status %>
    			<td><%= link_to "Accept", accept_invite_path(rec_invite), method: :put %> | 
  						<%= link_to "Decline", decline_invite_path(rec_invite), method: :put %> </td>
					<td><%= link_to "Details", rec_invite %> </td>
    		</tr>
    		<% end %>
    	</tbody>
    </table>
    
  </div>
  <div id="sent" class="tab-pane fade">
    <h3>Sent</h3>
    <table class="table table-striped">
    	<thead>
    		<tr>
    			<th>To</th>
    			<th>Event</th>
    			<th>Date & Time</th>
    			<th>Status</th>
    			<th>View</th>
    		</tr>
    	</thead>
    	<tbody>
    		<% @sent_invitations.each do |sent_invite| %>
    		<tr>
    			<td><%= link_to sent_invite.invitee.full_name, sent_invite.invitee %></td>
    			<td><%= link_to sent_invite.event.title, sent_invite.event %></td>
    			<td><%= sent_invite.event.datetime.localtime.strftime('%m/%d/%Y, %l:%M %p') %></td>
    			<td><%= sent_invite.status %>
					<td><%= link_to "Details", sent_invite %> </td>
    		</tr>
    		<% end %>
    	</tbody>
    </table>
  </div>

</div>

app/views/event_invitations/new.html.erb
<h2>New Invitation</h2>
<h3>Create Invitation for Event: <%= @event.title %></h3>
<% if @event.admin_or_creator?(current_user) %>
	<%= form_for @invitation do |f| %>
		<p>
			<%= f.label :invitee, "Invitee Email:" %>
			<%= f.text_field :invitee %>
		</p>
		<p>
			<%= f.hidden_field :event_id %>
		</p>
		<p>
			<%= f.submit 'Send Invite' %>
		</p>
	<% end %>
<% else %>
	<p>
		<strong>
			You are not authorized to invite people to this event. Only the host can invite users.
		</strong>
	</p>
<% end %>

app/views/event_invitations/show.html.erb
<div class="panel panel-primary">
	<div class="panel-heading">Invitation Details</div>
	<div class="panel-body">
		<p><strong>Title:</strong> <%= @invitation.event.title %></p>
		<p><strong>From:</strong> <%= link_to @invitation.inviter.full_name, @invitation.inviter %></p>
		<p><strong>Event Time:</strong> <%= @invitation.event.datetime.localtime.strftime('%m/%d/%Y, %l:%M %p') %></p>
		<p><strong>Location:</strong> <%= @invitation.event.location %></p>
		<p><strong>Status:</strong> <%= @invitation.status %></p>
		<p><%= link_to "Accept", accept_invite_path(@invitation), 
					 method: :put, class: "btn btn-#{@invitation.attending ? 'primary' : 'default'}" %>
			 <%= link_to "Decline", decline_invite_path(@invitation), 
					 method: :put, class: "btn btn-#{@invitation.attending ? 'default' : 'primary'}" %></p>
	 </div>
</div>