config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#index'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :events
  get    '/events/:id/invitation', to: 'event_invitations#new', as: 'new_invitation'
  post   'event_invitations' => 'event_invitations#create'
  
  get    '/events/:id/add_admin', to: 'event_managements#new', as: 'new_admin'
  post   'event_managements' => 'event_managements#create'

  get    '/invites', to: 'event_invitations#index', as: 'invites'

  put    '/invites/:id/accept', to: 'event_invitations#accept', as: 'accept_invite'
  put    '/invites/:id/decline', to: 'event_invitations#decline', as: 'decline_invite'
  get    '/invites/:id',         to: 'event_invitations#show', as: 'event_invitation'
end

app/views/layouts/_footer.html.erb
<footer class = "footer">
  <small>
    The Evently app
    by <a href="http://www.about.me/pmontalto">Patrick Montalto</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://www.github.com/patrickmontalto">GitHub</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <%= link_to image_tag("evently.png", height: 50, width: 300), root_path  %>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <% if signed_in? %>
        	<li><%= link_to "Create Event", new_event_path %></li>
        	<li><%= link_to "Events", events_path %></li>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.first_name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Invites", invites_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
  
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
      <%= render 'layouts/header' %>
      <div class="container container-compact ">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
        <%= yield %>
        <%= render 'layouts/footer' %>
        <%= debug(params) if Rails.env.development? %>
      </div>
  </body>
</html>